## Membaca dataset play-tennis

In [1]:
import pandas as p

In [55]:
tennis = p.read_csv("./tennis.csv")
tennis

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [59]:
tennis["outlook_"] = le.fit_transform(tennis["outlook"])
tennis["temp_"] = le.fit_transform(tennis["temp"])
tennis["humidity_"] = le.fit_transform(tennis["humidity"])
tennis["windy_"] = le.fit_transform(tennis["windy"])
tennis["play_"] = le.fit_transform(tennis["play"])
tennis

,outlook,temp,humidity,windy,play,outlook_,temp_,humidity_,windy_,play_
0,sunny,hot,high,False,no,2,1,0,0,0
1,sunny,hot,high,True,no,2,1,0,1,0
2,overcast,hot,high,False,yes,0,1,0,0,1
3,rainy,mild,high,False,yes,1,2,0,0,1
4,rainy,cool,normal,False,yes,1,0,1,0,1
5,rainy,cool,normal,True,no,1,0,1,1,0
6,overcast,cool,normal,True,yes,0,0,1,1,1
7,sunny,mild,high,False,no,2,2,0,0,0
8,sunny,cool,normal,False,yes,2,0,1,0,1
9,rainy,mild,normal,False,yes,1,2,1,0,1
10,sunny,mild,normal,True,yes,2,2,1,1,1
11,overcast,mild,high,True,yes,0,2,0,1,1
12,overcast,hot,normal,False,yes,0,1,1,0,1
13,rainy,mild,high,True,no,1,2,0,1,0

In [60]:
x = tennis.iloc[:,5:-1].values
y = tennis.iloc[:,-1].values
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size = 0.1)
x_train

array([[0, 0, 1, 1],
       [2, 1, 0, 1],
       [1, 2, 0, 1],
       [1, 0, 1, 0],
       [0, 2, 0, 1],
       [2, 2, 0, 0],
       [0, 1, 1, 0],
       [1, 2, 1, 0],
       [1, 0, 1, 1],
       [2, 0, 1, 0],
       [0, 1, 0, 0],
       [2, 2, 1, 1]], dtype=int64)

In [64]:
from sklearn.naive_bayes import GaussianNB as NB
gnb = NB()
gnb.fit(x_train,y_train)
y_predict = gnb.predict(x_test)
y_predict

array([0, 1])

In [65]:
y_test

array([0, 1])